module.exports = [
  {
    id: "mock-001",
    title: "布拉格 3 区街角店铺转租",
    category: "shop",
    intent: "offer",
    tier: "normal",
    city: "布拉格",
    district: "Prague 3",
    areaText: "42 平米",
    priceText: "月租 32,000 CZK",
    depositText: "押金 2 个月",
    availableFrom: "2025-05-01",
    minStayText: "一年起",
    contactName: "林先生",
    contactLine: "WeChat: lin-shop-prg",
    description: "临街铺位，适合奶茶、烘焙、小吃。普通帖无图展示，感兴趣请直接加微信看视频。",
    imageFileIds: [],
    localImagePaths: [],
    imageCount: 0,
    durationDays: 30,
    status: "active",
    moderationState: "pass",
    adminNote: "",
    createdBy: "mock-user-2",
    createdAt: "2025-03-01T10:00:00.000Z",
    updatedAt: "2025-03-01T10:00:00.000Z",
    expireAt: "2025-03-31T10:00:00.000Z"
  },
  {
    id: "mock-002",
    title: "求租能做外卖的小店面",
    category: "shop",
    intent: "wanted",
    tier: "normal",
    city: "布尔诺",
    district: "市中心",
    areaText: "30-60 平米",
    priceText: "预算 25,000 CZK 内",
    depositText: "可谈",
    availableFrom: "尽快",
    minStayText: "一年以上",
    contactName: "陈女士",
    contactLine: "WeChat: brno-food-space",
    description: "优先考虑可外卖、可带排烟位置，附近有学生区更好。",
    imageFileIds: [],
    localImagePaths: [],
    imageCount: 0,
    durationDays: 30,
    status: "active",
    moderationState: "pass",
    adminNote: "",
    createdBy: "mock-user-1",
    createdAt: "2025-03-03T13:20:00.000Z",
    updatedAt: "2025-03-03T13:20:00.000Z",
    expireAt: "2025-04-02T13:20:00.000Z"
  },
  {
    id: "mock-003",
    title: "老城单间短租，可按周住",
    category: "flex",
    intent: "offer",
    tier: "normal",
    city: "布拉格",
    district: "Prague 1",
    areaText: "单间",
    priceText: "900 CZK / 晚",
    depositText: "无押金",
    availableFrom: "2025-04-18",
    minStayText: "3 晚起",
    contactName: "周先生",
    contactLine: "WeChat: oldtown-room",
    description: "离景点近，适合短期旅游和找房过渡。包水电网，可协助入住指引。",
    imageFileIds: ["cloud://demo/image-1"],
    localImagePaths: [],
    imageCount: 1,
    durationDays: 15,
    status: "active",
    moderationState: "pass",
    adminNote: "",
    createdBy: "mock-user-3",
    createdAt: "2025-03-06T09:00:00.000Z",
    updatedAt: "2025-03-06T09:00:00.000Z",
    expireAt: "2025-03-21T09:00:00.000Z"
  },
  {
    id: "mock-004",
    title: "VIP 帖：布拉格 5 区两室一厅转租",
    category: "flex",
    intent: "offer",
    tier: "vip",
    city: "布拉格",
    district: "Prague 5",
    areaText: "2+1",
    priceText: "26,500 CZK / 月",
    depositText: "押一付一",
    availableFrom: "2025-05-10",
    minStayText: "1 个月起",
    contactName: "王女士",
    contactLine: "WeChat: vip-flat-prg5",
    description: "管理员代为升级的 VIP 帖，可放更多图片，可延长有效期。",
    imageFileIds: ["cloud://demo/image-2", "cloud://demo/image-3", "cloud://demo/image-4"],
    localImagePaths: [],
    imageCount: 3,
    durationDays: 120,
    status: "active",
    moderationState: "pass",
    adminNote: "VIP 用户，支持 120 天展示。",
    createdBy: "mock-user-1",
    createdAt: "2025-03-08T18:00:00.000Z",
    updatedAt: "2025-03-08T18:00:00.000Z",
    expireAt: "2025-07-06T18:00:00.000Z"
  },
  {
    id: "mock-005",
    title: "奥洛穆茨学生区求租短租房",
    category: "flex",
    intent: "wanted",
    tier: "normal",
    city: "奥洛穆茨",
    district: "学校附近",
    areaText: "单人间或 studio",
    priceText: "预算 13,000 CZK 内",
    depositText: "可商量",
    availableFrom: "2025-06-01",
    minStayText: "2 个月起",
    contactName: "刘同学",
    contactLine: "WeChat: olomouc-room",
    description: "优先考虑安静、安全、步行可到校区的位置。",
    imageFileIds: [],
    localImagePaths: [],
    imageCount: 0,
    durationDays: 15,
    status: "active",
    moderationState: "pass",
    adminNote: "",
    createdBy: "mock-user-4",
    createdAt: "2025-03-10T12:00:00.000Z",
    updatedAt: "2025-03-10T12:00:00.000Z",
    expireAt: "2025-03-25T12:00:00.000Z"
  },
  {
    id: "mock-006",
    title: "俄斯特拉发整套公寓月租",
    category: "flex",
    intent: "offer",
    tier: "normal",
    city: "俄斯特拉发",
    district: "市中心",
    areaText: "1+1",
    priceText: "17,500 CZK / 月",
    depositText: "押金 1 个月",
    availableFrom: "2025-05-20",
    minStayText: "1 个月起",
    contactName: "赵先生",
    contactLine: "WeChat: ostrava-flat",
    description: "适合短期落脚或工作过渡，交通方便，生活设施齐全。",
    imageFileIds: ["cloud://demo/image-5"],
    localImagePaths: [],
    imageCount: 1,
    durationDays: 15,
    status: "active",
    moderationState: "pass",
    adminNote: "",
    createdBy: "mock-user-5",
    createdAt: "2025-03-11T08:30:00.000Z",
    updatedAt: "2025-03-11T08:30:00.000Z",
    expireAt: "2025-03-26T08:30:00.000Z"
  }
];
